name: projectap
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: '>=3.0.0 <4.0.0'

dependencies:
    flutter:
        sdk: flutter

    just_audio: ^0.9.38
    cupertino_icons: ^1.0.8
    file_picker: ^8.0.3
    http: ^1.2.2
    local_auth: ^2.2.0
    fluttertoast: ^8.2.4
    shared_preferences: ^2.2.2
    email_validator: ^2.1.17
    google_fonts: ^6.2.1
    animate_do: ^3.3.4
    flutter_spinkit: ^5.2.1
    lottie: ^3.1.2
    id3: ^1.0.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.1

flutter:
    uses-material-design: true
